version: "2"
services:
  goservice:
    build: goservice
    ports:
      - "4200:4200"
  nodeservice:
    build: nodeservice
    init: true
    ports:
      - "4000:4000"
  reactfrontend:
    build: reactfrontend
    ports:
      - "3000:3000"
  gomqttemitter:
    build: gomqttemitter
  nodemqttemitter:
    build: nodemqttemitter
  gocollector:
    build: gocollector
